- packages/core/src/agent/didcomm/v2/DIDResolverService.ts
- packages/core/src/modules/dids/__tests__/__fixtures__/didSovWJz9mHyW9BZksioQnRsrAo.json
- packages/core/src/modules/dids/domain/service/DidCommV2Service.ts
- packages/core/src/modules/dids/methods/indy/IndyDidResolver.ts
- packages/core/src/modules/dids/methods/indy/__tests__/IndyDidResolver.test.ts
- packages/core/src/modules/ledger/services/IndyLedgerService.ts
- Corrected DIDComm DIDResolver implementation to include all relevant fields retrieved from aries-framework-core DidResolverService.
- Corrected type filed value of DIDComm v2 service entries of DID documents.
>  #790: Correct DIDComm DIDResolver implementation

- packages/core/src/agent/didcomm/v2/DIDResolverService.ts
- packages/core/src/agent/didcomm/v2/__tests__/DIDResolverService.test.ts
- Corrected service entries conversion in DIDResolverService.
- Added unit tests for DIDResolverService verifying service entries conversion.
> #790: Corrected DIDResolverService, added tests

- packages/core/package.json
- packages/core/src/agent/MessageSender.ts
- packages/core/src/modules/out-of-band/services/OutOfBandService.ts
- packages/core/src/modules/routing/RecipientModule.ts
- packages/core/src/modules/value-transfer/services/ValueTransferService.ts
Fix for issue with non working WS connection when using WSS endpoint.
> Bugfix/Fix transports priority for WS mediator connection

- packages/core/package.json
- packages/core/src/modules/value-transfer/services/ValueTransferService.ts
- yarn.lock
Done in scope of sicpa-dlab/cbdc-projects/issues/1176
> #1176/Fix pending transaction abort

- packages/core/src/modules/routing/RecipientModule.ts
- packages/core/src/modules/routing/services/MediationRecipientService.ts
- packages/core/src/transport/WsOutboundTransport.ts
- sicpa-dlab/cbdc-projects/issues/1192
> #1192/Add workaround for non-working mediator WS connection in case of multiple mediation requests

- demo/package.json
- demo/src/Anna.ts
- demo/src/BaseAgent.ts
- demo/src/Bob.ts
- demo/src/Carol.ts
- demo/src/CentralBank.ts
- demo/src/CentralBankIssuer.ts
- demo/src/GlobalBank.ts
- demo/src/LocalBank.ts
- packages/core/package.json
- packages/core/src/agent/Agent.ts
- packages/core/src/modules/dids/domain/Did.ts
- packages/core/src/modules/dids/services/DidService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferWitnessService.ts
- packages/core/src/modules/well-known/models/DidInfo.ts
- packages/core/src/modules/witness-gossip/repository/WitnessStateRecord.ts
Ticket: https://github.com/sicpa-dlab/cbdc-projects/issues/1324
> Use single did for witness/gossip

- demo/package.json
- packages/core/package.json
- packages/core/src/modules/gossip/service/GossipTransportService.ts
- packages/core/src/modules/value-transfer/ValueTransferModule.ts
- packages/core/src/modules/value-transfer/services/ValueTransferCryptoService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferGetterService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferGiverService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferIssuerService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferTransportService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferWitnessService.ts
#1385: Generate new DID's for every transaction
#1251: Send Gossip Message unencrypted
> #1385: Generate new DID's for every transaction + #1251: Send Gossip Message unencrypted

- package.json
**Related ticket on Github:** none
- @nadraliev
- @spivachuk
Bump version of node-gyp to one that seems to work on M1
> [Build][Mac M1] Fix node gyp m1

- packages/core/package.json
- packages/core/src/modules/gossip/service/GossipTransportService.ts
**Related ticket on Github:** [#1490](https://github.com/sicpa-dlab/cbdc-projects/issues/1490)
- @dmitry-vychikov
- @spivachuk 
Added workaround to use encrypted message for `WitnessTableMessage` type.
> #1490/Fix witness table query

- packages/core/package.json
- packages/core/src/modules/value-transfer/logger/SicpaAriesLogger.ts
- packages/core/src/modules/value-transfer/logger/index.ts
- packages/core/src/modules/value-transfer/services/ValueTransferGetterService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferGiverService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferIssuerService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferLoggerService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferTransportService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferWitnessService.ts
**Related ticket on Github:** #https://github.com/sicpa-dlab/cbdc-projects/issues/1508
- @nadraliev
- @spivachuk 
> [AFJ] [Logs] Context loggers

- .github/PULL_REQUEST_TEMPLATE.md
- demo/package.json
- demo/src/BaseAgent.ts
- demo/src/Bob.ts
- emulator/package.json
- packages/core/package.json
- @spivachuk
Update dependency on VTP package
> Updated version of VTP library to 0.2.7

- demo/package.json
- emulator/package.json
- packages/core/package.json
- packages/core/src/modules/value-transfer/services/ValueTransferCryptoService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferGetterService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferGiverService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferWitnessService.ts
- yarn.lock
**Related ticket on Github:** https://github.com/sicpa-dlab/cbdc-projects/issues/1551
- @dmitry-vychikov 
Updated implementation of VTP Crypto Service to implement new required method
> Added check for DID existence before accepting Offer/Request

- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/modules/connections/ConnectionEvents.ts
- packages/core/src/modules/connections/ConnectionsModule.ts
- packages/core/src/modules/connections/models/ShareContactRequest.ts
- packages/core/src/modules/connections/services/ShareContactService.ts
- packages/core/src/modules/out-of-band/services/OutOfBandService.ts
- packages/core/src/utils/__tests__/regex.test.ts
- packages/core/src/utils/parseInvitation.ts
- packages/core/src/utils/regex.ts
- yarn.lock
**Related ticket on Github:** [#1546](https://github.com/sicpa-dlab/cbdc-projects/issues/1546)
- @Artemkaaas
- @dmitry-vychikov 
Updated Share Contact API to pass contact label from client side, added contact invitation label parsing (according to Share Contact protocol spec).
> #1546/Update Share Contact API and add contact invitation label parsing

- packages/core/package.json
- packages/core/src/modules/routing/MediatorModule.ts
- packages/core/src/modules/routing/protocol/pickup/v1/MessagePickupService.ts
- packages/core/src/modules/routing/protocol/pickup/v1/handlers/BatchHandler.ts
- packages/core/src/modules/routing/protocol/pickup/v1/messages/BatchAckMessage.ts
- packages/core/src/modules/routing/protocol/pickup/v1/messages/index.ts
**Related ticket on Github:** [#1545](https://github.com/sicpa-dlab/cbdc-projects/issues/1545)
- @Artemkaaas
- @dmitry-vychikov
Added custom ACK header to batch DIDComm message.
Added ACK handling
> DIDComm ACK

- packages/core/package.json
- packages/core/src/modules/routing/RecipientModule.ts
- yarn.lock
**Related ticket on Github:**
- https://github.com/sicpa-dlab/cbdc-projects/issues/1576
- @dmitry-vychikov 
- @Artemkaaas 
Small update to skip mediator WS reconnect/messages pickup when Internet connection is not available.
> #1576/Skip mediator reconnect/messages pickup if offline

- .github/workflows/continuous-deployment.yml
- packages/peer-did-ts/LICENSE
- packages/peer-did-ts/package.json
- @Artemkaaas
- @spivachuk
- Added peer-did-ts publishing to NPM.
- Commented out publishing of other packages.
> Added peer-did-ts publishing to NPM

- packages/peer-did-ts/README.md
> Updated README in peer-did-ts package

- packages/peer-did-ts/package.json
> Incremented peer-did-ts package version

- demo/package.json
- emulator/package.json
- packages/core/package.json
- packages/node/package.json
- yarn.lock
> Update VTP/Gossip packages

- packages/core/package.json
- packages/core/src/modules/value-transfer/services/ValueTransferGetterService.ts
- packages/core/src/modules/value-transfer/services/ValueTransferGiverService.ts
**Related ticket on Github:** 
https://github.com/sicpa-dlab/cbdc-projects/issues/1650
https://github.com/sicpa-dlab/cbdc-projects/issues/1704
- @dmitry-vychikov 
> Fix verification events

- demo/package.json
- packages/core/package.json
- packages/core/src/agent/Agent.ts
- packages/core/src/agent/AgentConfig.ts
- packages/core/src/modules/routing/messages/MediationRequestMessage.ts
- packages/core/src/types.ts
- packages/node/package.json
- packages/react-native/package.json
**Related ticket on Github:** 
> Version bump 4
